# At one point I was deploying this using Google App Engine.
# Then I discovered it would be cheaper to use my tiny cloud VM.

runtime: go112

instance_class: B1

automatic_scaling:
  max_instances: 1

handlers:
  - url: /chat
    script: auto
  - url: /hello
    script: auto
  - url: /
    static_files: static/index.html
    upload: static/index.html
  - url: /.*
    static_dir: static
 
network:
  session_affinity: true
