name: Build/Push

on:
  push:
    branches:
      - main
      - master
    tags:
      - v*

jobs:
  publish:
    name: Publish container images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Retrieve code
        uses: actions/checkout@v2

      - name: Gitlab variables
        id: vars
        run: build/gitlab-vars

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # Currently required, because buildx doesn't support auto-push from docker
      - name: Set up builder
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: build/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}
